name: Update gist with WakaTime stats
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Run manually"
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 971a8fffde46c421e6bfae8e8ffab3d9
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
